CURRENCY_ALGO = "ALGO"
EXCHANGE_ALGORAND_BLOCKCHAIN = "algorand_blockchain"

TRANSACTION_TYPE_PAYMENT = "pay"
TRANSACTION_TYPE_ASSET_TRANSFER = "axfer"
TRANSACTION_TYPE_APP_CALL = "appl"
TRANSACTION_TYPE_ASSET_CONFIG = "acfg"
TRANSACTION_TYPE_KEY_REGISTRATION = "keyreg"

TRANSACTION_KEY_PAYMENT = "payment-transaction"
TRANSACTION_KEY_ASSET_TRANSFER = "asset-transfer-transaction"
TRANSACTION_KEY_APP_CALL = "application-transaction"
