CURRENCY_ALGO = "ALGO"
EXCHANGE_ALGORAND_BLOCKCHAIN = "algorand_blockchain"

TRANSACTION_TYPE_PAYMENT = "pay"
TRANSACTION_TYPE_ASSET_TRANSFER = "axfer"
TRANSACTION_TYPE_APP_CALL = "appl"

APPLICATION_ID_TINYMAN_v10 = 350338509
APPLICATION_ID_TINYMAN_v11 = 552635992

APPLICATION_ID_YIELDLY = 233725848
APPLICATION_ID_YIELDLY_NLL = 233725844
APPLICATION_ID_YIELDLY_YLDY_ALGO_POOL = 233725850
APPLICATION_ID_YIELDLY_YLDY_OPUL_POOL = 348079765
APPLICATION_ID_YIELDLY_OPUL_OPUL_POOL = 367431051
APPLICATION_ID_YIELDLY_YLDY_SMILE_POOL = 352116819
APPLICATION_ID_YIELDLY_SMILE_SMILE_POOL = 373819681
APPLICATION_ID_YIELDLY_YLDY_ARCC_POOL = 385089192
APPLICATION_ID_YIELDLY_ARRC_ARCC_POOL = 498747685
APPLICATION_ID_YIELDLY_YLDY_GEMS_POOL = 393388133
APPLICATION_ID_YIELDLY_GEMS_GEMS_POOL = 419301793
APPLICATION_ID_YIELDLY_YLDY_XET_POOL = 424101057
APPLICATION_ID_YIELDLY_XET_XET_POOL = 470390215
APPLICATION_ID_YIELDLY_YLDY_CHOICE_POOL = 447336112
APPLICATION_ID_YIELDLY_CHOICE_CHOICE_POOL = 464365150
APPLICATION_ID_YIELDLY_YLDY_AKITA_POOL = 511597182
APPLICATION_ID_YIELDLY_YLDY_ARCC_T5_POOL = 583357499
APPLICATION_ID_YIELDLY_YLDY_DEFLY_POOL = 591414576
APPLICATION_ID_YIELDLY_YLDY_KTNC_POOL = 593126242
APPLICATION_ID_YIELDLY_YLDY_TINY_POOL = 593270704
APPLICATION_ID_YIELDLY_YLDY_TREES_POOL = 593289960
APPLICATION_ID_YIELDLY_YLDY_HDL_POOL = 596950925
APPLICATION_ID_YIELDLY_YLDY_BLOCK_POOL = 593324268
APPLICATION_ID_YIELDLY_AKITA_LP_POOL = 511593477
APPLICATION_ID_YIELDLY_XET_LP_POOL = 568949192
APPLICATION_ID_YIELDLY_ARCC_LP_POOL = 583355704
APPLICATION_ID_YIELDLY_DEFLY_LP_POOL = 591416743
APPLICATION_ID_YIELDLY_KTNC_LP_POOL = 593133882
APPLICATION_ID_YIELDLY_TINY_LP_POOL = 593278929
APPLICATION_ID_YIELDLY_TREES_LP_POOL = 593294372
APPLICATION_ID_YIELDLY_HDL_LP_POOL = 596954871
APPLICATION_ID_YIELDLY_BLOCK_LP_POOL = 593337625

YIELDLY_APPLICATIONS = [
    APPLICATION_ID_YIELDLY,
    APPLICATION_ID_YIELDLY_NLL,
    APPLICATION_ID_YIELDLY_YLDY_ALGO_POOL,
    APPLICATION_ID_YIELDLY_YLDY_OPUL_POOL,
    APPLICATION_ID_YIELDLY_OPUL_OPUL_POOL,
    APPLICATION_ID_YIELDLY_YLDY_SMILE_POOL,
    APPLICATION_ID_YIELDLY_SMILE_SMILE_POOL,
    APPLICATION_ID_YIELDLY_YLDY_ARCC_POOL,
    APPLICATION_ID_YIELDLY_ARRC_ARCC_POOL,
    APPLICATION_ID_YIELDLY_YLDY_GEMS_POOL,
    APPLICATION_ID_YIELDLY_GEMS_GEMS_POOL,
    APPLICATION_ID_YIELDLY_YLDY_XET_POOL,
    APPLICATION_ID_YIELDLY_XET_XET_POOL,
    APPLICATION_ID_YIELDLY_YLDY_CHOICE_POOL,
    APPLICATION_ID_YIELDLY_CHOICE_CHOICE_POOL,
    APPLICATION_ID_YIELDLY_YLDY_AKITA_POOL,
    APPLICATION_ID_YIELDLY_YLDY_ARCC_T5_POOL,
    APPLICATION_ID_YIELDLY_YLDY_DEFLY_POOL,
    APPLICATION_ID_YIELDLY_YLDY_KTNC_POOL,
    APPLICATION_ID_YIELDLY_YLDY_TINY_POOL,
    APPLICATION_ID_YIELDLY_YLDY_TREES_POOL,
    APPLICATION_ID_YIELDLY_YLDY_HDL_POOL,
    APPLICATION_ID_YIELDLY_YLDY_BLOCK_POOL,
    APPLICATION_ID_YIELDLY_AKITA_LP_POOL,
    APPLICATION_ID_YIELDLY_XET_LP_POOL,
    APPLICATION_ID_YIELDLY_ARCC_LP_POOL,
    APPLICATION_ID_YIELDLY_DEFLY_LP_POOL,
    APPLICATION_ID_YIELDLY_KTNC_LP_POOL,
    APPLICATION_ID_YIELDLY_TINY_LP_POOL,
    APPLICATION_ID_YIELDLY_TREES_LP_POOL,
    APPLICATION_ID_YIELDLY_HDL_LP_POOL,
    APPLICATION_ID_YIELDLY_BLOCK_LP_POOL,
]

TINYMAN_TRANSACTION_SWAP = "c3dhcA=="           # "swap"
TINYMAN_TRANSACTION_REDEEM = "cmVkZWVt"         # "redeem"
TINYMAN_TRANSACTION_LP_ADD = "bWludA=="         # "mint"
TINYMAN_TRANSACTION_LP_REMOVE = "YnVybg=="      # "burn"

YIELDLY_TRANSACTION_POOL_CLAIM = "Q0E="
YIELDLY_TRANSACTION_POOL_CLOSE = "Q0FX"
