CURRENCY_ALGO = "ALGO"
EXCHANGE_ALGORAND_BLOCKCHAIN = "algorand_blockchain"

TRANSACTION_TYPE_PAYMENT = "pay"
TRANSACTION_TYPE_ASSET_TRANSFER = "axfer"
TRANSACTION_TYPE_APP_CALL = "appl"
TRANSACTION_TYPE_ASSET_CONFIG = "acfg"
TRANSACTION_TYPE_KEY_REGISTRATION = "keyreg"

TRANSACTION_KEY_PAYMENT = "payment-transaction"
TRANSACTION_KEY_ASSET_TRANSFER = "asset-transfer-transaction"
TRANSACTION_KEY_APP_CALL = "application-transaction"


ALGOFI_TRANSACTION_SWAP_EXACT_FOR = "c2Vm"   # "sef"
PACT_TRANSACTION_SWAP = "U1dBUA=="           # "SWAP"
WAGMISWAP_TRANSACTION_SWAP = "c3dhcA=="      # "swap"
# TODO find a better solution when they release their SDK
HUMBLESWAP_TRANSACTION = "Aw=="

APPL_ARGS_SWAP = {
    ALGOFI_TRANSACTION_SWAP_EXACT_FOR: "AlgoFi",
    PACT_TRANSACTION_SWAP: "Pact",
    WAGMISWAP_TRANSACTION_SWAP: "WagmiSwap",
    HUMBLESWAP_TRANSACTION: "HumbleSwap",
}
