CURRENCY_ALGO = "ALGO"
EXCHANGE_ALGORAND_BLOCKCHAIN = "algorand_blockchain"

ASSET_ID_ALGO = 0

TRANSACTION_TYPE_PAYMENT = "pay"
TRANSACTION_TYPE_ASSET_TRANSFER = "axfer"
TRANSACTION_TYPE_APP_CALL = "appl"
TRANSACTION_TYPE_ASSET_CONFIG = "acfg"
TRANSACTION_TYPE_KEY_REGISTRATION = "keyreg"

TRANSACTION_KEY_PAYMENT = "payment-transaction"
TRANSACTION_KEY_ASSET_TRANSFER = "asset-transfer-transaction"
TRANSACTION_KEY_APP_CALL = "application-transaction"

# Algostake escrow wallet: https://algostake.org/litepaper
ADDRESS_ALGOSTAKE_ESCROW = "4ZK3UPFRJ643ETWSWZ4YJXH3LQTL2FUEI6CIT7HEOVZL6JOECVRMPP34CY"
ADDRESS_ALGOMINT = "ETGSQKACKC56JWGMDAEP5S2JVQWRKTQUVKCZTMPNUGZLDVCWPY63LSI3H4"
ADDRESS_PACT_REWARDS = "PACTC5CQVKK6F43TPYII2WED72BXYIQ5OF7DKQREDOY4UXCYJRMGGQ5IQQ"
ADDRESS_FOLKS_REWARDS = "OW3VJ3YSECTNTJ73GNQE2LYOQUMMAV577NDNF53SXRKB33OST6NNTPRD4Y"
ADDRESS_PERA = "V73GWLED56UUKKGOESJYHQADILUFMDM4RIBZZOLOOR4RKONZFDXYTVPMRM"
